<?xml version="1.0" encoding="UTF-8" standalone="yes" ?><?codewarrior exportversion="1.0.1" ideversion="5.0" ?><!DOCTYPE PROJECT [<!ELEMENT PROJECT (TARGETLIST, TARGETORDER, GROUPLIST, DESIGNLIST?)><!ELEMENT TARGETLIST (TARGET+)><!ELEMENT TARGET (NAME, SETTINGLIST, FILELIST?, LINKORDER?, SEGMENTLIST?, OVERLAYGROUPLIST?, SUBTARGETLIST?, SUBPROJECTLIST?, FRAMEWORKLIST?)><!ELEMENT NAME (#PCDATA)><!ELEMENT USERSOURCETREETYPE (#PCDATA)><!ELEMENT PATH (#PCDATA)><!ELEMENT FILELIST (FILE*)><!ELEMENT FILE (PATHTYPE, PATHROOT?, ACCESSPATH?, PATH, PATHFORMAT?, ROOTFILEREF?, FILEKIND?, FILEFLAGS?)><!ELEMENT PATHTYPE (#PCDATA)><!ELEMENT PATHROOT (#PCDATA)><!ELEMENT ACCESSPATH (#PCDATA)><!ELEMENT PATHFORMAT (#PCDATA)><!ELEMENT ROOTFILEREF (PATHTYPE, PATHROOT?, ACCESSPATH?, PATH, PATHFORMAT?)><!ELEMENT FILEKIND (#PCDATA)><!ELEMENT FILEFLAGS (#PCDATA)><!ELEMENT FILEREF (TARGETNAME?, PATHTYPE, PATHROOT?, ACCESSPATH?, PATH, PATHFORMAT?)><!ELEMENT TARGETNAME (#PCDATA)><!ELEMENT SETTINGLIST ((SETTING|PANELDATA)+)><!ELEMENT SETTING (NAME?, (VALUE|(SETTING+)))><!ELEMENT PANELDATA (NAME, VALUE)><!ELEMENT VALUE (#PCDATA)><!ELEMENT LINKORDER (FILEREF*)><!ELEMENT SEGMENTLIST (SEGMENT+)><!ELEMENT SEGMENT (NAME, ATTRIBUTES?, FILEREF*)><!ELEMENT ATTRIBUTES (#PCDATA)><!ELEMENT OVERLAYGROUPLIST (OVERLAYGROUP+)><!ELEMENT OVERLAYGROUP (NAME, BASEADDRESS, OVERLAY*)><!ELEMENT BASEADDRESS (#PCDATA)><!ELEMENT OVERLAY (NAME, FILEREF*)><!ELEMENT SUBTARGETLIST (SUBTARGET+)><!ELEMENT SUBTARGET (TARGETNAME, ATTRIBUTES?, FILEREF?)><!ELEMENT SUBPROJECTLIST (SUBPROJECT+)><!ELEMENT SUBPROJECT (FILEREF, SUBPROJECTTARGETLIST)><!ELEMENT SUBPROJECTTARGETLIST (SUBPROJECTTARGET*)><!ELEMENT SUBPROJECTTARGET (TARGETNAME, ATTRIBUTES?, FILEREF?)><!ELEMENT FRAMEWORKLIST (FRAMEWORK+)><!ELEMENT FRAMEWORK (FILEREF, LIBRARYFILE?, VERSION?)><!ELEMENT LIBRARYFILE (FILEREF)><!ELEMENT VERSION (#PCDATA)><!ELEMENT TARGETORDER (ORDEREDTARGET|ORDEREDDESIGN)*><!ELEMENT ORDEREDTARGET (NAME)><!ELEMENT ORDEREDDESIGN (NAME, ORDEREDTARGET+)><!ELEMENT GROUPLIST (GROUP|FILEREF)*><!ELEMENT GROUP (NAME, (GROUP|FILEREF)*)><!ELEMENT DESIGNLIST (DESIGN+)><!ELEMENT DESIGN (NAME, DESIGNDATA)><!ELEMENT DESIGNDATA (#PCDATA)>]><PROJECT>    <TARGETLIST>        <TARGET>            <NAME>MacSurf</NAME>            <SETTINGLIST>                <!-- Settings for "Source Trees" panel -->                <SETTING><NAME>UserSourceTrees</NAME><VALUE></VALUE></SETTING>                <!-- Settings for "Access Paths" panel -->                <SETTING><NAME>AlwaysSearchUserPaths</NAME><VALUE>true</VALUE></SETTING>                <SETTING><NAME>InterpretDOSAndUnixPaths</NAME><VALUE>true</VALUE></SETTING>                <SETTING><NAME>RequireFrameworkStyleIncludes</NAME><VALUE>false</VALUE></SETTING>                <SETTING><NAME>UserSearchPaths</NAME>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>Back40:Desktop Folder:patrick:macsurf-source Folder:browser:libcss:include:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>Back40:Desktop Folder:patrick:macsurf-source Folder:browser:libdom:bindings:hubbub:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>Back40:Desktop Folder:patrick:macsurf-source Folder:browser:libnsbmp:include:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>Back40:Desktop Folder:patrick:macsurf-source Folder:browser:libwapcaplet:include:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>Back40:Desktop Folder:patrick:macsurf-source Folder:browser:libnsgif:include:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>Back40:Desktop Folder:patrick:macsurf-source Folder:browser:libnsgif:src:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>Back40:Desktop Folder:patrick:macsurf-source Folder:browser:libduktape:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>Back40:Desktop Folder:patrick:macsurf-source Folder:browser:netsurf:frontends:macos9:javascript:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>Back40:Desktop Folder:patrick:macsurf-source Folder:browser:netsurf:frontends:macos9:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>Back40:Desktop Folder:patrick:macsurf-source Folder:browser:libwapcaplet:src:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>Back40:Desktop Folder:patrick:macsurf-source Folder:browser:netsurf:frontends:macos9:shims:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>Back40:Desktop Folder:patrick:macsurf-source Folder:browser:netsurf:frontends:macos9:sys:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>Back40:Desktop Folder:patrick:macsurf-source Folder:browser:netsurf:frontends:macos9:arpa:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>Back40:Desktop Folder:patrick:macsurf-source Folder:browser:netsurf:frontends:macos9:netinet:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>Back40:Desktop Folder:patrick:macsurf-source Folder:browser:netsurf:frontends:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>Back40:Desktop Folder:patrick:macsurf-source Folder:browser:netsurf:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>Back40:Desktop Folder:patrick:macsurf-source Folder:browser:netsurf:include:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>Back40:Desktop Folder:patrick:macsurf-source Folder:browser:netsurf:utils:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>Back40:Desktop Folder:patrick:macsurf-source Folder:browser:netsurf:utils:http:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>Back40:Desktop Folder:patrick:macsurf-source Folder:browser:netsurf:utils:nsurl:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>Back40:Desktop Folder:patrick:macsurf-source Folder:browser:netsurf:desktop:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>Back40:Desktop Folder:patrick:macsurf-source Folder:browser:netsurf:content:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>Back40:Desktop Folder:patrick:macsurf-source Folder:browser:netsurf:content:handlers:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>Back40:Desktop Folder:patrick:macsurf-source Folder:browser:netsurf:content:handlers:html:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>Back40:Desktop Folder:patrick:macsurf-source Folder:browser:netsurf:content:handlers:css:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>Back40:Desktop Folder:patrick:macsurf-source Folder:browser:libparserutils:include:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>Back40:Desktop Folder:patrick:macsurf-source Folder:browser:libparserutils:src:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>Back40:Desktop Folder:patrick:macsurf-source Folder:browser:libparserutils:src:charset:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>Back40:Desktop Folder:patrick:macsurf-source Folder:browser:libparserutils:src:charset:codecs:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>Back40:Desktop Folder:patrick:macsurf-source Folder:browser:libparserutils:src:charset:encodings:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>Back40:Desktop Folder:patrick:macsurf-source Folder:browser:libparserutils:src:input:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>Back40:Desktop Folder:patrick:macsurf-source Folder:browser:libhubbub:include:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>Back40:Desktop Folder:patrick:macsurf-source Folder:browser:libhubbub:src:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>Back40:Desktop Folder:patrick:macsurf-source Folder:browser:libhubbub:src:charset:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>Back40:Desktop Folder:patrick:macsurf-source Folder:browser:libhubbub:src:tokeniser:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>                    </SETTING>                    <SETTING>                        <SETTING><NAME>SearchPath</NAME>                            <SETTING><NAME>Path</NAME><VALUE>Back40:Desktop Folder:patrick:macsurf-source Folder:browser:libhubbub:src:treebuilder:</VALUE></SETTING>                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>                            <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>                        </SETTING>                        <SETTING><NAME>Recursive</NAME><VALUE>false</VALUE></SETTING>                        <SETTING><NAME>Fram